build: spad_regression_research.tex references.bib
	pdflatex spad_regression_research.tex
	biber spad_regression_research
	pdflatex spad_regression_research.tex

clean:
	rm *.aux *.log *.pdf *.xml *.bcf *.bbl *.blg *.out
